-- Verificar triggers relacionadas à tabela config
SELECT RDB$TRIGGER_NAME, RDB$RELATION_NAME, RDB$TRIGGER_TYPE, RDB$TRIGGER_SOURCE
FROM RDB$TRIGGERS 
WHERE UPPER(TRIM(RDB$RELATION_NAME)) = 'CONFIG' 
OR UPPER(RDB$TRIGGER_NAME) LIKE '%CONFIG%';
QUIT;



